import { APP_NAME } from "@/lib/constants";

/**
 * Every user-facing string lives here (§02: English-only in v1, but
 * centralised so localisation later is a config change, not a rewrite).
 * Voice rules (§7.6): sentence case, no exclamation marks, no emoji.
 * Errors say what happened and what to do; empty states invite action.
 */
export const copy = {
  signIn: {
    title: "Sign in",
    subtitle: `Enter your email and we'll send you a link to sign in to ${APP_NAME}.`,
    emailLabel: "Email",
    emailPlaceholder: "you@example.com",
    submit: "Send magic link",
    sending: "Sending link…",
    sentPrefix: "Check your email — we sent a sign-in link to",
    resend: "Use a different email",
    errorSend: "Couldn't send the link. Check your email address and try again.",
    errorCallback: "That link didn't work. Request a new one below.",
  },
  nav: {
    library: "Library",
    add: "Add",
    search: "Search",
    stats: "Stats",
  },
  library: {
    title: "Library",
    emptyMessage:
      "Nothing here yet. Tap Add and start with a decade you remember well.",
    noResultsForFilter: "No films match these filters. Clear a filter and try again.",
    sortLabel: "Sort",
    sort: {
      recent_added: "Recently added",
      recent_watched: "Recently watched",
      release_year: "Release year",
      rating: "Rating",
      title: "A–Z",
    },
    filterLabel: "Filter",
    filter: {
      decade: "Decade",
      genre: "Genre",
      director: "Director",
      rated: "Rated",
      unrated: "Unrated",
      allDecades: "All decades",
      allGenres: "All genres",
      allDirectors: "All directors",
      allRatings: "All",
      tag: "Tag",
      allTags: "All tags",
      clear: "Clear filters",
      apply: "Apply",
    },
    contextMenu: {
      logAnother: "Log another viewing",
      edit: "Edit",
      remove: "Remove from library",
    },
    removeConfirmTitle: (title: string, count: number) =>
      `Remove ${title} and its ${count} viewing${count === 1 ? "" : "s"}?`,
    removeConfirmBody: "This can't be undone.",
    removeAction: "Remove",
    cancelAction: "Cancel",
  },
  account: {
    signOut: "Sign out",
  },
  errors: {
    signInRequired: "Sign in to search the film database.",
    rateLimited: "Too many searches at once. Wait a moment and try again.",
    tmdbUnreachable: "Couldn't reach the film database. Check your connection and try again.",
    invalidQuery: "Type a title to search.",
    filmNotFound: "Couldn't find that film.",
    entrySaveFailed: "Couldn't save that viewing. Check your connection and try again.",
    libraryLoadFailed: "Couldn't load your library. Check your connection and try again.",
    importFailed: "Couldn't process that import. Check your connection and try again.",
    exportFailed: "Couldn't export your library. Check your connection and try again.",
    retry: "Try again",
  },
  search: {
    title: "Search",
    placeholder: "Search films",
    emptyPrompt: "Search for a film to see if you've watched it.",
    noResults: "No results for",
    seenLabel: "Seen",
  },
  film: {
    logAViewing: "Log a viewing",
    yourHistory: "Your viewing history",
    synopsis: "Synopsis",
    noHistoryYet: "You haven't logged a viewing yet.",
    editViewing: "Edit viewing",
    deleteViewing: "Delete viewing",
    deleteViewingConfirm: "Delete this viewing? This can't be undone.",
  },
  logViewing: {
    title: "Log a viewing",
    editTitle: "Edit viewing",
    saveChanges: "Save changes",
    whenLabel: "When",
    whenToday: "Today",
    whenPickDate: "Pick a date",
    whenYear: "Just the year",
    whenRoughly: "Roughly",
    whenUnknown: "Don't remember",
    dateLabel: "Date",
    yearLabel: "Year",
    eraLabel: "What was going on?",
    eraPlaceholder: "as a kid",
    eraSuggestions: ["as a kid", "at university", "during lockdown"],
    ratingLabel: "Rating",
    noteLabel: "Note",
    notePlaceholder: "What do you remember about it?",
    more: "More",
    placeLabel: "Where",
    placePlaceholder: "cinema, on a plane",
    companyLabel: "Who with",
    companyPlaceholder: "with my brother",
    tagsLabel: "Tags",
    tagsPlaceholder: "Add a tag and press enter",
    removeTag: "Remove tag",
    submit: "Log a viewing",
    saving: "Saving…",
    close: "Close",
  },
  wall: {
    title: "Add films",
    done: "Done",
    noResults: "No films found for this year.",
    addedCount: (n: number) => `${n} film${n === 1 ? "" : "s"} added`,
    offline: "Offline — changes will sync",
  },
  stats: {
    title: "Stats",
    emptyMessage: "Nothing to show yet. Log a few films and check back.",
    filmsPerYear: "Films per year",
    decadesWatched: "Decades watched",
    mostSeenDirectors: "Most-seen directors",
    totalHours: "Total hours watched",
    longestGap: "Longest gap between rewatches",
    firstLogged: "First film logged",
    lastLogged: "Most recent film logged",
    daysSuffix: (n: number) => `${n} day${n === 1 ? "" : "s"} apart`,
    loadFailed: "Couldn't load your stats. Check your connection and try again.",
  },
  settings: {
    title: "Settings",
    accountSection: "Account",
    signedInAs: "Signed in as",
    appearanceSection: "Appearance",
    appearanceSystem: "System",
    appearanceLight: "Light",
    appearanceDark: "Dark",
    importSection: "Import",
    importDescription: "Bring in your history from Letterboxd or IMDb.",
    exportSection: "Export",
    exportDescription: "Download a full copy of your library — for backup, or to move elsewhere.",
    exportJson: "Export as JSON",
    exportCsv: "Export as CSV",
    dangerSection: "Danger zone",
    deleteAccount: "Delete account",
    deleteAccountConfirmTitle: "Delete your account?",
    deleteAccountConfirmBody: "Every film, viewing, and note is deleted permanently. This can't be undone.",
    deleteAccountAction: "Delete account",
    aboutSection: "About",
    tmdbAttribution: "This product uses the TMDB API but is not endorsed or certified by TMDB.",
  },
  import: {
    title: "Import",
    chooseFile: "Choose a file",
    dropHint:
      "A Letterboxd diary.csv or watched.csv, an IMDb ratings export, or a SEEN export. diary.csv also brings your ratings.",
    parsing: "Reading file…",
    unrecognisedFormat:
      "Couldn't recognise that file. Export a Letterboxd watched.csv, an IMDb ratings export, or a SEEN export, and try again.",
    matching: "Matching",
    matchBatchFailed: "Couldn't match that batch. Check your connection and try again.",
    retryBatch: "Retry",
    reviewTitle: "Review import",
    matchedLabel: "Matched",
    ambiguousLabel: "Needs a pick",
    unmatchedLabel: "Not found",
    skip: "Skip",
    skipped: "Skipped",
    pick: "Pick",
    confirmImport: "Import",
    importing: "Importing…",
    commitFailed: "Couldn't finish the import. Check your connection and try again — nothing already imported was lost.",
    nothingToImport: "Nothing to import.",
  },
} as const;
