import { APP_NAME } from "@/lib/constants";

/**
 * Every user-facing string lives here (§02: English-only in v1, but
 * centralised so localisation later is a config change, not a rewrite).
 * Voice rules (§7.6): sentence case, no exclamation marks, no emoji.
 * Errors say what happened and what to do; empty states invite action.
 */
export const copy = {
  signIn: {
    title: "Sign in",
    subtitle: `Enter your email and we'll send you a link to sign in to ${APP_NAME}.`,
    emailLabel: "Email",
    emailPlaceholder: "you@example.com",
    submit: "Send magic link",
    sending: "Sending link…",
    sentPrefix: "Check your email — we sent a sign-in link to",
    resend: "Use a different email",
    errorSend: "Couldn't send the link. Check your email address and try again.",
    errorCallback: "That link didn't work. Request a new one below.",
  },
  nav: {
    library: "Library",
    add: "Add",
    search: "Search",
    stats: "Stats",
  },
  library: {
    title: "Library",
    emptyMessage:
      "Nothing here yet. Tap Add and start with a decade you remember well.",
    noResultsForFilter: "No films match these filters.",
    sortLabel: "Sort",
    sort: {
      recent_added: "Recently added",
      recent_watched: "Recently watched",
      release_year: "Release year",
      rating: "Rating",
      title: "A–Z",
    },
    filterLabel: "Filter",
    filter: {
      decade: "Decade",
      genre: "Genre",
      director: "Director",
      rated: "Rated",
      unrated: "Unrated",
      allDecades: "All decades",
      allGenres: "All genres",
      allDirectors: "All directors",
      allRatings: "All",
      clear: "Clear filters",
      apply: "Apply",
    },
    contextMenu: {
      logAnother: "Log another viewing",
      edit: "Edit",
      remove: "Remove from library",
    },
    removeConfirmTitle: (title: string, count: number) =>
      `Remove ${title} and its ${count} viewing${count === 1 ? "" : "s"}?`,
    removeConfirmBody: "This can't be undone.",
    removeAction: "Remove",
    cancelAction: "Cancel",
  },
  placeholder: {
    stats: "Stats isn't built yet — it lands in a later milestone.",
  },
  account: {
    signOut: "Sign out",
  },
  errors: {
    signInRequired: "Sign in to search the film database.",
    rateLimited: "Too many searches at once. Wait a moment and try again.",
    tmdbUnreachable: "Couldn't reach the film database. Check your connection and try again.",
    invalidQuery: "Type a title to search.",
    filmNotFound: "Couldn't find that film.",
    entrySaveFailed: "Couldn't save that viewing. Check your connection and try again.",
    libraryLoadFailed: "Couldn't load your library. Check your connection and try again.",
    retry: "Try again",
  },
  search: {
    title: "Search",
    placeholder: "Search films",
    emptyPrompt: "Search for a film to see if you've watched it.",
    noResults: "No results for",
    seenLabel: "Seen",
  },
  film: {
    logAViewing: "Log a viewing",
    yourHistory: "Your viewing history",
    synopsis: "Synopsis",
    noHistoryYet: "You haven't logged a viewing yet.",
    editViewing: "Edit viewing",
    deleteViewing: "Delete viewing",
    deleteViewingConfirm: "Delete this viewing? This can't be undone.",
  },
  logViewing: {
    title: "Log a viewing",
    editTitle: "Edit viewing",
    saveChanges: "Save changes",
    whenLabel: "When",
    whenToday: "Today",
    whenPickDate: "Pick a date",
    whenYear: "Just the year",
    whenRoughly: "Roughly",
    whenUnknown: "Don't remember",
    dateLabel: "Date",
    yearLabel: "Year",
    eraLabel: "What was going on?",
    eraPlaceholder: "as a kid",
    eraSuggestions: ["as a kid", "at university", "during lockdown"],
    ratingLabel: "Rating",
    noteLabel: "Note",
    notePlaceholder: "What do you remember about it?",
    more: "More",
    placeLabel: "Where",
    placePlaceholder: "cinema, on a plane",
    companyLabel: "Who with",
    companyPlaceholder: "with my brother",
    submit: "Log a viewing",
    saving: "Saving…",
    close: "Close",
  },
  wall: {
    title: "Add films",
    done: "Done",
    noResults: "No films found for this year.",
    addedCount: (n: number) => `${n} film${n === 1 ? "" : "s"} added`,
  },
} as const;
